name: // saroz
title: The C Programming Language
author:
  name: Saroj Kumar Poddar
  email: hello@evoytic.com
url: saroz.github.io/c-programming

permalink: :slug

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

collections:
  - navs
sass:
  sass_dir: _sass
include:
  - string.md
  - add-two-numbers.md
  - add-two-user-input-numbers.md